### ISSUE TITLE
Hello, the link you gave me is no longer valid

### ISSUE THREAD

**Issue by roweir** [yaomingdan/xSirrioNx-js-xlsx#1]

**Comment by yaomingdan** [comment]
can not   install ?  give me some  detail.

**Comment by roweir** [comment]
After installation, which file do I need to reference

**Comment by yaomingdan** [comment]
1) npm install git+https://github.com/yaomingdan/xSirrioNx-js-xlsx.git
2)then，your  package.json ->dependencies    has  "xlsx": "git+https://github.com/yaomingdan/xSirrioNx-js-xlsx.git"
3)in  your .js reuqire like this ：const XLSX = require('xlsx');
how  to  use  this mudule ，see the  README.md
