### ISSUE TITLE
 need the example code for Inserting jpg or png pictures 

### ISSUE THREAD

**Issue by myseemylife** [yaomingdan/xSirrioNx-js-xlsx#2]
The JsFiddle link in Readme is broken now,
i check you sourcecode,but don't know how to make  insert imgs to work.need a tiny complete example ,Please help

**Comment by yaomingdan** [comment]
是导出excel的时候插入图片是吗？
EN:It is to insert pictures when exporting excel, right?

**Comment by yaomingdan** [comment]
我把我项目里的代码给你看看，jsfiddle写起来太麻烦了。
helper.js

```js
import XLSX from 'xlsx';
import {
  deepCopy//这个自己实现，就是个对象深拷贝而已
} from "../../../util";
const isBoolean = maybeBoolean => typeof maybeBoolean === 'boolean';
const isNumber = maybeNumber => typeof maybeNumber === 'number';
const isString = maybeString => typeof maybeString === 'string';
const isObject = maybeObject => maybeObject !== null && typeof maybeObject === 'object';
const isCellDescriptor = maybeCell => isObject(maybeCell) && 'v' in maybeCell;

const originDate = new Date(Date.UTC(1899, 11, 30));

const buildExcelDate = (value, is1904) => {
  const epoch = Date.parse(value + (is1904 ? 1462 : 0));
  return (epoch - originDate) / (864e5);
};

const buildSheetFromMatrix = (data, options = {}) => {
  const workSheet = {};
  const range = {
    s: {
      c: 1e7,
      r: 1e7
    },
    e: {
      c: 0,
      r: 0
    }
  };

  if (!Array.isArray(data)) throw new Error('sheet data is not array');

  for (let R = 0; R !== data.length; R += 1) {
    for (let C = 0; C !== data[R].length; C += 1) {
      if (!Array.isArray(data[R])) throw new Error(`${R}th row data is not array`);

      if (range.s.r > R) range.s.r = R;
      if (range.s.c > C) range.s.c = C;
      if (range.e.r < R) range.e.r = R;
      if (range.e.c < C) range.e.c = C;
      if (data[R][C] === null) {
        continue; // eslint-disable-line
      }
      const cell = isCellDescriptor(data[R][C]) ? data[R][C] : {
        v: data[R][C]
      };
      const cellRef = XLSX.utils.encode_cell({
        c: C,
        r: R
      });
      if (isNumber(cell.v)) {
        cell.t = 'n';
      } else if (isBoolean(cell.v)) {
        cell.t = 'b';
      } else if (cell.v instanceof Date) {
        cell.t = 'n';
        cell.v = buildExcelDate(cell.v);
        cell.z = cell.z || XLSX.SSF._table[14]; // eslint-disable-line no-underscore-dangle
      } else {
        cell.t = 's';
      }
      cell.s = {
        alignment: {
          horizontal: "center",
          vertical: "center",
          wrapText: 1
        },
        fill: {
          patternType: "none",
          fgColor: {
            rgb: "FF000000"
          },
          bgColor: {
            rgb: "FF8DB4E2"
          }
        },
        border: {
          top: {
            style: "thin",
            color: {
              auto: 1
            }
          },
          right: {
            style: "thin",
            color: {
              auto: 1
            }
          },
          bottom: {
            style: "thin",
            color: {
              auto: 1
            }
          },
          left: {
            style: "thin",
            color: {
              auto: 1
            }
          }
        }
      }
      if (isNumber(cell.z)) cell.z = XLSX.SSF._table[cell.z]; // eslint-disable-line no-underscore-dangle
      workSheet[cellRef] = cell;
    }
  }
  if (range.s.c < 1e7) {
    workSheet['!ref'] = XLSX.utils.encode_range(range);
  }
  // if (options['!cols']) {
  //   workSheet['!cols'] = options['!cols'];
  // }
  if (options['!merges']) {
    if (options['!merges'] === "auto") {
      options['!merges'] = [];
      let temp_data = deepCopy(data);
      for (let R = 0; R !== temp_data.length; R += 1) { //行
        for (let C = 0; C !== temp_data[R].length; C += 1) { //列
          temp_data[R][C] = {
            V: temp_data[R][C],
            R,
            C
          }
        }
      }
      //矩阵行列置换
      let matrix_data = temp_data[0].map(function (col, i) {
        return temp_data.map(function (row) {
          return row[i];
        })
      });
      for (let R = 0; R !== matrix_data.length; R += 1) { //行
        let s = null;
        let e = null;
        let repeat = 1;
        for (let C = 1; C !== matrix_data[R].length; C += 1) { //列
          let cell = matrix_data[R][C];
          let pre_cell = matrix_data[R][C - 1];
          if (pre_cell.V === cell.V && !s && pre_cell.V !== "" && cell.V !== "") {
            s = {
              c: pre_cell.C,
              r: pre_cell.R,
            }
            repeat++;
          }
          if (pre_cell.V !== cell.V) {
            if (s && repeat > 1) {
              e = {
                c: pre_cell.C,
                r: pre_cell.R,
              }
              options['!merges'].push(deepCopy({
                s,
                e
              }));
            }
            s = null;
            e = null;
            repeat = 1;
          }
        }
      }
    }
    workSheet['!merges'] = options['!merges'];

  }
  for (let name in options) {
    workSheet[name] = options[name]
  }
  let datapng = `iVBORw0KGgoAAAANSUhEUgAAADsAAAAhCAYAAABnaNNOAAAKT0lEQVRYhXVZbbIkNQ6UZPcbBiL4wdE5DtfgAHuIDWBmumwhKVOuml3oeP26usof+kilJLf++tvvLqKSL3WTvVe8t+z4vt3F875uySt3lVXPtGZ4vV1MOV/vuxJjzYYMHTHW4u31XDk2X+45dp97zv2wGP6pKcdJrOXxNq4j9c5xa3nJunfvm2OgVo7t+TOeiW/HRjuVWqVATean+i1MKgqhrAziUAOCxX9TKGChZG7sFMphzbYrBLj1PsphZM7DehA2p0LGbWlcjqVlclnbQjnjvXN+3Sj5hXNnefEoG1byi0q48K82K8FLjRizU4O4CiQ4PalhcVg/3mHZ1HAYNE3vCK2b+z1fjZJ+DlB4fa0VY1/l/uW4dMhQuTHgUA7WxHMPdGoiMK+3wOLh2b1WwABbrlRWRj3LQQRk/VvbsVl5tz9vg6RHNZRMO+xY4GWEkcO65nr837ByPeLSoFAhYallMMvFhEuVQT3C7NrwGlwecnPNDBc4TuR6OMbp3Xm987bFzZXgk8thpYJrCmuEsCLmMmaBgFTCqKyHACHUiKscb1DmZemNne4ErIWe1hu55WjGeu5Vj8wfVqA3yxAh1QCC1rXKg2mUK+aXkunLXfaRd+qUumyhI7fMP5YB17lAPFn1EN+TeIpe6hNee8VmlySJpeBDdnghDVVWXVLxhDhJ5kBMv4KoFrAopk1kWugxo1ba2kUYbEBXSWAZf9e65Jo5ZJOYtJyTml2axgaiCp10mHsbEpCef359kzyk2LYtb9w4NyyPpv92W9wpTCiZm4fVOk6tqMszGMqzI+9VyDSd2YnPWqM8nnE+CgXpoUNMAkgWCSZKSIdEb6xr5SDZuJ+GgH0qsMAGNJjFs/kOz7yvq+CgD1ofQQIWA3OxWLK8C0jrccTICLeEKzbPEJv8XvNDm6le8xFBMGKTVHnYL6AqPFfrppI6Y18oWTyRc43sa5AxH4wReAuDj7HJJwiLd0D8WvtQGAwZsn3LHNWBnUoxkdiV+QqeGVPBjLHA1AFvhZadDnLzzG2AqBdTbzLbO5RR+KPWwxwah6lic50O1O2BtuQDbaYntY2b5KQyW+47ZQZXjNofHJKEey0onNewbIy7NiY5WSNjsSEkFCrlGALYFGCSWWPcxZSTBJIp52p5qbRyDSuCs7o/KkU5/eyP/9JBxrSysA5hVA4g2eT1a87auxwSDz7i+wgHGAnt2lYIqiwS72T4maxb2heEgfQO4lUMCFGugm14IcYVryYJTLC4F6SExcgu7fSRN1Mg73JHUMSc6qY1cTmfMBTj0rpaCqKjfF2xiYJKU85v11v0zdxMQqg9mVGsiookmfToWieH9uKIjU47AkY2Yc70YlMt2t+V+9o0uwn2lIZddp6vtzfNzs3jRcPe5h1KQ+YrKC/jO3khjKyVfFeFwHV1noaTUJ3ts5GRrOb6uoo2TuXSQmkrLUX9SiFSKfIca145RcapbZ+17onFf34dL4uffYcrCYmCj7xnQXwB17j/ERwyBgyecSkF0w1Scqy5OlRcWU+Hwb58CfcnQK1JoC3b9I6NS3CTUxuXTgtGqHRx6lylw+CxZt5/U1ofCh+XM/U1ZGeSZHjxI5ZMRV9DK2wyVIx1dJLmNBQXO+T6kuXlwnVKkKXr/Ou9AMcQLi0wLq9AT7rOz2Ie7+6jY4Tlm9+KtHKNylYu7/9vPVzhwqpIqV8KY3MUbF8xZ6Y8hGwWMq9pqLXNTvlZAE0D1EChcb2UHKHk12DfqrRYKM2v+y4eRtz9OD0M4qLSwxYW1KEombpYsSqgrkc7fpnEOx/KI/6lU9XN8pWvw8gzFH29Zs3LYiQVTN3Sk5mv8125tyo2qdRSdUytsLjPXRtnT/YR8vuoPqGgHmzMgW4QPFm42qNv7GSsnqGA7zKWSnS7lzGij+oKFFAKGMnGDSWkYUh4BrSRsZg5ckx+lpKZNx3etsc+yiKjDE+DK1INkoiepqIKDMqW41KO+ZoQRg2BPNujaZWi710WzkI+U0IKo8KEv0GBKWR3R11eFYuOZyNth7i0BUivlnKIzRLIkHoKmWUoZ22BYF7dFDRv1H6plJ49lvR4J+8AQfOnzy/4qKCWyr5gTTbhxY6G3lSZi/MZBLPT+HcsVk5rguNnt19ACWQyQlsHi33GbhYfsxTEusUjySFjAqL75oNnT7t7vqAAgsGtiKsfzJ9+mHB1bT6OEHihQrH0NCsiA66QKqrlYjnnTN5dX7M8hFuyEJmML3hsMM8sW4UMVFvoipqF81in2DhLwUSUJS/MuncOHKrWXqVsvzt9llOOJrHOjz+8Dt2fQka7nIHgQ/3cexwhoR41k65foaSenKmNhlRQ+wCHPlZcS7K+cbdHrytMe9qKC0KjG5ImIgIUih5gVwY++1Vb2Mr2BjXZADl9nGhB+P8/MBu8LCFYheCYqWPlwQfVZOh9z9vig/OBmua/4sBuMhTMnA1zIydj7eRuBYxb3tKAIVdikSPmL5+HPF/tXenP3DiF4CmCiZ5xg4rWd7WDjl6h59Q8n+yMaBRMQj+szQd3PkIE4L5J19GEp9CorK1decLpfMYeGjkT0qYs8+fP83gLVPEoAFhIj/aEy7F+K6vdZz7r6c6l1L6he5igK4+qf/sBDLC94fqAdhufhjUeoLXhRXt8I6u9TFmZ8+fPn0YRwfFG4dvP5vk/i//qHbn4aK/wbNDlAdlOL/2fQgz1c/JgDxRU2+gtsN5GEiFhsW9OQ4xON7fxDhk+5DUqyh0P9KMJnGyzUDEss2OdPvcCHNsED8X1Jv9W+4719jTEW3efwzKmYbiPQeqU8FRwMNyuhp91kpFdFe1nK9YdcHt2Ux6hUYVnYvM/f/y3DqoKroZiIQuoVLROKRR1srQQW5gW7LTgcII/lLs90B58Etvt9BuujQZvT2nHHnO7dwEhZHM95HLI7HjX69ANxcU+0sxrAxTOhL0Zk6nsrNOjeLo7Su90oC7fvVCw7AMr6U+nAXYXAmz9iIzBTNjQbWOpbirrd6xrV1uI+4bylofBuPbm/c3j1Lw7s10ChTdpdIa9+9s8n21Jt8pZWnWJSOc7CGrHKL1eAwyWX11fgzmyszhG6F8VnAfr5aEDennk3kxTi7m3H+kZIzzAr1p64Zw7X/PTnL0zi+2F7+48Rr098nzdKUq/u3Z6tY49E4IGJdJgpVAf13ZXZOs+uXhwwPm5gHK1gTb6tfJsnVn6Kf+Pm3P8Ki7Qpij81jPHOMpWjXkC4Z4vow+dH3Uw/Hdrz5aoTxURv/idRUlCDTjkTpZ7tu9erxHTP6QpGoH7uGhL12hL5RjB2WpiZ+eROOXMMBg4Yp06mJg3XX+SBpTvdqmV7YKgY+92Nb16fi45VuC4xfRild5W979M/HqPPtnAn8FYWzAfbK5DKQtFdZbWvzDivPtGHq5n5tC11kkXi+dRh1Ufpwk8rD1QW/7+Dt61eR/hnH4TFY6QqdnjVGFQvyCCqsmmeH6fEDaG9GiPnD6q+M9PhN4+Q08qVPyeDGVgvb8B9ip+T3qnEfIAAAAASUVORK5CYII=`
  workSheet["!images"] = [{
    name: 'image.png',
    data: datapng,
    opts: {
      base64: true
    },
    type: "png",
    position: {
      type: 'twoCellAnchor',
      attrs: {
        editAs: 'oneCell'
      },
      from: {
        col: 3,
        row: 3
      },
      to: {
        col: 6,
        row: 6
      }
    }
  }];
  return workSheet;
};

export default {
  buildSheetFromMatrix,
  isBoolean,
  isNumber,
  isString,
  isObject,
  isCellDescriptor
};
```
index.js
```js
import XLSX from 'xlsx';
import helpers from './helpers';
let buildSheetFromMatrix = helpers.buildSheetFromMatrix
let isString = helpers.isString

function parse(mixed, options = {}) {

  const workSheet = XLSX[isString(mixed) ? 'readFile' : 'read'](mixed, {
    cellDates: true
  });
  return Object.keys(workSheet.Sheets).map((name) => {
    const sheet = workSheet.Sheets[name];
    return {
      name,
      data: XLSX.utils.sheet_to_json(sheet, {
        header: 1,
        raw: true
      }),
      worksheet: workSheet
    };
  });
}

function build(worksheets, options = {}) {
  const defaults = {
    bookType: 'xlsx',
    bookSST: false,
    type: 'binary'
  };
  const workBook = new Workbook();
  worksheets.forEach((worksheet) => {
    const name = worksheet.name || 'Sheet';
    const data = buildSheetFromMatrix(worksheet.data || [], options);
    workBook.SheetNames.push(name);
    workBook.Sheets[name] = data;
  });
  options.Custprops && (workBook.Custprops = options.Custprops);
  options.Props && (workBook.Props = options.Props);
  return XLSX.write(workBook, Object.assign({}, defaults, options));
}

function writeFile(worksheets, filename, options = {}) {
  const defaults = {
    bookType: 'xlsx',
    bookSST: false,
    type: 'binary'
  };
  const workBook = new Workbook();
  worksheets.forEach((worksheet) => {
    const name = worksheet.name || 'Sheet';
    const data = buildSheetFromMatrix(worksheet.data || [], options);
    workBook.SheetNames.push(name);
    workBook.Sheets[name] = data;
  });
  options.Custprops && (workBook.Custprops = options.Custprops);
  options.Props && (workBook.Props = options.Props);
  let excel_data = XLSX.write(workBook, Object.assign({}, defaults, options));
  let buf = new ArrayBuffer(excel_data.length);
  let bufView = new Uint8Array(buf);
  for (var i = 0; i < excel_data.length; ++i) {
    bufView[i] = excel_data.charCodeAt(i) & 255;
  }
  const elink = document.createElement("a"); // 创建a标签
  elink.download = filename;
  elink.style.display = "none";
  const blob = new Blob([buf], {
    type: "application/octet-stream"
  });
  elink.href = URL.createObjectURL(blob);
  document.body.appendChild(elink);
  elink.click(); // 触发点击a标签事件
  document.body.removeChild(elink);
}
let Workbook = function () {
  this.SheetNames = [];
  this.Sheets = {};
}
export default {
  parse,
  writeFile,
  build
};
```
这个两个文件，在你项目excel文件夹下新建一下，导出的案例是：
```js
import node_xlsx from "./excel/index";
```
然后在你具体的按钮事件里面调用即可。我的项目并没有用到图片功能，我在helper里面给你加了图片的，你借鉴一下。
```js
let ws = {};
          ws["!rows"] = [
            {
              hidden: false
            }
          ];
          ws["!cols"] = [];
          ws.Custprops = {};
          let data = [
            this.format_ins_view_column.map(i => {
              return i.title;
            }),
            ...deepCopy(this.filterdata_distinct)
              .filter(row => {
                if (this.cmdb.ins_view_selectedIds.size == 0) {
                  return true;
                }
                return this.cmdb.ins_view_selectedIds.has(row.ins.id);
              })
              .map(row => {
                let temp = [];
                this.format_ins_view_column.map(i => {
                  temp.push(get_attr_value(row[i.key]));
                });
                return temp;
              })
          ];
          for (var n = 0; n != data[0].length; ++n) {
            ws["!cols"].push({
              wpx: 150
            });
          }
          ws["!merges"] = "auto";
          let excel_data = node_xlsx.writeFile(
            [
              {
                name: "视图数据",
                data: data
              }
            ],
            "视图数据导出" +
              new Date() +
              ".xlsx",
            ws
          );
```
最终效果：
![image](https://user-images.githubusercontent.com/6559625/66897651-041fdb00-f02a-11e9-9d33-66a6ffb607bb.png)

**Comment by roweir** [comment]
收到，非常感谢，过两天我好好看看，这两天工作内容很多，到时候不懂有问题可能还得请教一下你哈




------------------ 原始邮件 ------------------
发件人: "姚明丹"<notifications@github.com>;
发送时间: 2019年10月16日(星期三) 下午3:31
收件人: "yaomingdan/xSirrioNx-js-xlsx"<xSirrioNx-js-xlsx@noreply.github.com>;
抄送: "Subscribed"<subscribed@noreply.github.com>;
主题: Re: [yaomingdan/xSirrioNx-js-xlsx]  need the example code forInserting jpg or png pictures  (#2)




我把我项目里的代码给你看看，jsfiddle写起来太麻烦了。
 helper.js
 
`import XLSX from 'xlsx';
 import {
 oneOf,
 deepCopy
 } from "../../../util";
 const isBoolean = maybeBoolean => typeof maybeBoolean === 'boolean';
 const isNumber = maybeNumber => typeof maybeNumber === 'number';
 const isString = maybeString => typeof maybeString === 'string';
 const isObject = maybeObject => maybeObject !== null && typeof maybeObject === 'object';
 const isCellDescriptor = maybeCell => isObject(maybeCell) && 'v' in maybeCell;
 
const originDate = new Date(Date.UTC(1899, 11, 30));
 
const buildExcelDate = (value, is1904) => {
 const epoch = Date.parse(value + (is1904 ? 1462 : 0));
 return (epoch - originDate) / (864e5);
 };
 
const buildSheetFromMatrix = (data, options = {}) => {
 const workSheet = {};
 const range = {
 s: {
 c: 1e7,
 r: 1e7
 },
 e: {
 c: 0,
 r: 0
 }
 };
 
if (!Array.isArray(data)) throw new Error('sheet data is not array');
 
for (let R = 0; R !== data.length; R += 1) {
 for (let C = 0; C !== data[R].length; C += 1) {
 if (!Array.isArray(data[R])) throw new Error(${R}th row data is not array);
   if (range.s.r > R) range.s.r = R;   if (range.s.c > C) range.s.c = C;   if (range.e.r < R) range.e.r = R;   if (range.e.c < C) range.e.c = C;   if (data[R][C] === null) {     continue; // eslint-disable-line   }   const cell = isCellDescriptor(data[R][C]) ? data[R][C] : {     v: data[R][C]   };   const cellRef = XLSX.utils.encode_cell({     c: C,     r: R   });   if (isNumber(cell.v)) {     cell.t = 'n';   } else if (isBoolean(cell.v)) {     cell.t = 'b';   } else if (cell.v instanceof Date) {     cell.t = 'n';     cell.v = buildExcelDate(cell.v);     cell.z = cell.z || XLSX.SSF._table[14]; // eslint-disable-line no-underscore-dangle   } else {     cell.t = 's';   }   cell.s = {     alignment: {       horizontal: "center",       vertical: "center",       wrapText: 1     },     fill: {       patternType: "none",       fgColor: {         rgb: "FF000000"       },       bgColor: {         rgb: "FF8DB4E2"       }     },     border: {       top: {         style: "thin",         color: {           auto: 1         }       },       right: {         style: "thin",         color: {           auto: 1         }       },       bottom: {         style: "thin",         color: {           auto: 1         }       },       left: {         style: "thin",         color: {           auto: 1         }       }     }   }   if (isNumber(cell.z)) cell.z = XLSX.SSF._table[cell.z]; // eslint-disable-line no-underscore-dangle   workSheet[cellRef] = cell; }  
}
 if (range.s.c < 1e7) {
 workSheet['!ref'] = XLSX.utils.encode_range(range);
 }
 // if (options['!cols']) {
 //   workSheet['!cols'] = options['!cols'];
 // }
 if (options['!merges']) {
 if (options['!merges'] === "auto") {
 options['!merges'] = [];
 let temp_data = deepCopy(data);
 for (let R = 0; R !== temp_data.length; R += 1) { //行
 for (let C = 0; C !== temp_data[R].length; C += 1) { //列
 temp_data[R][C] = {
 V: temp_data[R][C],
 R,
 C
 }
 }
 }
 //矩阵行列置换
 let matrix_data = temp_data[0].map(function (col, i) {
 return temp_data.map(function (row) {
 return row[i];
 })
 });
 for (let R = 0; R !== matrix_data.length; R += 1) { //行
 let s = null;
 let e = null;
 let repeat = 1;
 for (let C = 1; C !== matrix_data[R].length; C += 1) { //列
 let cell = matrix_data[R][C];
 let pre_cell = matrix_data[R][C - 1];
 if (pre_cell.V === cell.V && !s && pre_cell.V !== "" && cell.V !== "") {
 s = {
 c: pre_cell.C,
 r: pre_cell.R,
 }
 repeat++;
 }
 if (pre_cell.V !== cell.V) {
 if (s && repeat > 1) {
 e = {
 c: pre_cell.C,
 r: pre_cell.R,
 }
 options['!merges'].push(deepCopy({
 s,
 e
 }));
 }
 s = null;
 e = null;
 repeat = 1;
 }
 }
 }
 }
 workSheet['!merges'] = options['!merges'];
 
}
 for (let name in options) {
 workSheet[name] = options[name]
 }
 let datapng = iVBORw0KGgoAAAANSUhEUgAAADsAAAAhCAYAAABnaNNOAAAKT0lEQVRYhXVZbbIkNQ6UZPcbBiL4wdE5DtfgAHuIDWBmumwhKVOuml3oeP26usof+kilJLf++tvvLqKSL3WTvVe8t+z4vt3F875uySt3lVXPtGZ4vV1MOV/vuxJjzYYMHTHW4u31XDk2X+45dp97zv2wGP6pKcdJrOXxNq4j9c5xa3nJunfvm2OgVo7t+TOeiW/HRjuVWqVATean+i1MKgqhrAziUAOCxX9TKGChZG7sFMphzbYrBLj1PsphZM7DehA2p0LGbWlcjqVlclnbQjnjvXN+3Sj5hXNnefEoG1byi0q48K82K8FLjRizU4O4CiQ4PalhcVg/3mHZ1HAYNE3vCK2b+z1fjZJ+DlB4fa0VY1/l/uW4dMhQuTHgUA7WxHMPdGoiMK+3wOLh2b1WwABbrlRWRj3LQQRk/VvbsVl5tz9vg6RHNZRMO+xY4GWEkcO65nr837ByPeLSoFAhYallMMvFhEuVQT3C7NrwGlwecnPNDBc4TuR6OMbp3Xm987bFzZXgk8thpYJrCmuEsCLmMmaBgFTCqKyHACHUiKscb1DmZemNne4ErIWe1hu55WjGeu5Vj8wfVqA3yxAh1QCC1rXKg2mUK+aXkunLXfaRd+qUumyhI7fMP5YB17lAPFn1EN+TeIpe6hNee8VmlySJpeBDdnghDVVWXVLxhDhJ5kBMv4KoFrAopk1kWugxo1ba2kUYbEBXSWAZf9e65Jo5ZJOYtJyTml2axgaiCp10mHsbEpCef359kzyk2LYtb9w4NyyPpv92W9wpTCiZm4fVOk6tqMszGMqzI+9VyDSd2YnPWqM8nnE+CgXpoUNMAkgWCSZKSIdEb6xr5SDZuJ+GgH0qsMAGNJjFs/kOz7yvq+CgD1ofQQIWA3OxWLK8C0jrccTICLeEKzbPEJv8XvNDm6le8xFBMGKTVHnYL6AqPFfrppI6Y18oWTyRc43sa5AxH4wReAuDj7HJJwiLd0D8WvtQGAwZsn3LHNWBnUoxkdiV+QqeGVPBjLHA1AFvhZadDnLzzG2AqBdTbzLbO5RR+KPWwxwah6lic50O1O2BtuQDbaYntY2b5KQyW+47ZQZXjNofHJKEey0onNewbIy7NiY5WSNjsSEkFCrlGALYFGCSWWPcxZSTBJIp52p5qbRyDSuCs7o/KkU5/eyP/9JBxrSysA5hVA4g2eT1a87auxwSDz7i+wgHGAnt2lYIqiwS72T4maxb2heEgfQO4lUMCFGugm14IcYVryYJTLC4F6SExcgu7fSRN1Mg73JHUMSc6qY1cTmfMBTj0rpaCqKjfF2xiYJKU85v11v0zdxMQqg9mVGsiookmfToWieH9uKIjU47AkY2Yc70YlMt2t+V+9o0uwn2lIZddp6vtzfNzs3jRcPe5h1KQ+YrKC/jO3khjKyVfFeFwHV1noaTUJ3ts5GRrOb6uoo2TuXSQmkrLUX9SiFSKfIca145RcapbZ+17onFf34dL4uffYcrCYmCj7xnQXwB17j/ERwyBgyecSkF0w1Scqy5OlRcWU+Hwb58CfcnQK1JoC3b9I6NS3CTUxuXTgtGqHRx6lylw+CxZt5/U1ofCh+XM/U1ZGeSZHjxI5ZMRV9DK2wyVIx1dJLmNBQXO+T6kuXlwnVKkKXr/Ou9AMcQLi0wLq9AT7rOz2Ie7+6jY4Tlm9+KtHKNylYu7/9vPVzhwqpIqV8KY3MUbF8xZ6Y8hGwWMq9pqLXNTvlZAE0D1EChcb2UHKHk12DfqrRYKM2v+y4eRtz9OD0M4qLSwxYW1KEombpYsSqgrkc7fpnEOx/KI/6lU9XN8pWvw8gzFH29Zs3LYiQVTN3Sk5mv8125tyo2qdRSdUytsLjPXRtnT/YR8vuoPqGgHmzMgW4QPFm42qNv7GSsnqGA7zKWSnS7lzGij+oKFFAKGMnGDSWkYUh4BrSRsZg5ckx+lpKZNx3etsc+yiKjDE+DK1INkoiepqIKDMqW41KO+ZoQRg2BPNujaZWi710WzkI+U0IKo8KEv0GBKWR3R11eFYuOZyNth7i0BUivlnKIzRLIkHoKmWUoZ22BYF7dFDRv1H6plJ49lvR4J+8AQfOnzy/4qKCWyr5gTTbhxY6G3lSZi/MZBLPT+HcsVk5rguNnt19ACWQyQlsHi33GbhYfsxTEusUjySFjAqL75oNnT7t7vqAAgsGtiKsfzJ9+mHB1bT6OEHihQrH0NCsiA66QKqrlYjnnTN5dX7M8hFuyEJmML3hsMM8sW4UMVFvoipqF81in2DhLwUSUJS/MuncOHKrWXqVsvzt9llOOJrHOjz+8Dt2fQka7nIHgQ/3cexwhoR41k65foaSenKmNhlRQ+wCHPlZcS7K+cbdHrytMe9qKC0KjG5ImIgIUih5gVwY++1Vb2Mr2BjXZADl9nGhB+P8/MBu8LCFYheCYqWPlwQfVZOh9z9vig/OBmua/4sBuMhTMnA1zIydj7eRuBYxb3tKAIVdikSPmL5+HPF/tXenP3DiF4CmCiZ5xg4rWd7WDjl6h59Q8n+yMaBRMQj+szQd3PkIE4L5J19GEp9CorK1decLpfMYeGjkT0qYs8+fP83gLVPEoAFhIj/aEy7F+K6vdZz7r6c6l1L6he5igK4+qf/sBDLC94fqAdhufhjUeoLXhRXt8I6u9TFmZ8+fPn0YRwfFG4dvP5vk/i//qHbn4aK/wbNDlAdlOL/2fQgz1c/JgDxRU2+gtsN5GEiFhsW9OQ4xON7fxDhk+5DUqyh0P9KMJnGyzUDEss2OdPvcCHNsED8X1Jv9W+4719jTEW3efwzKmYbiPQeqU8FRwMNyuhp91kpFdFe1nK9YdcHt2Ux6hUYVnYvM/f/y3DqoKroZiIQuoVLROKRR1srQQW5gW7LTgcII/lLs90B58Etvt9BuujQZvT2nHHnO7dwEhZHM95HLI7HjX69ANxcU+0sxrAxTOhL0Zk6nsrNOjeLo7Su90oC7fvVCw7AMr6U+nAXYXAmz9iIzBTNjQbWOpbirrd6xrV1uI+4bylofBuPbm/c3j1Lw7s10ChTdpdIa9+9s8n21Jt8pZWnWJSOc7CGrHKL1eAwyWX11fgzmyszhG6F8VnAfr5aEDennk3kxTi7m3H+kZIzzAr1p64Zw7X/PTnL0zi+2F7+48Rr098nzdKUq/u3Z6tY49E4IGJdJgpVAf13ZXZOs+uXhwwPm5gHK1gTb6tfJsnVn6Kf+Pm3P8Ki7Qpij81jPHOMpWjXkC4Z4vow+dH3Uw/Hdrz5aoTxURv/idRUlCDTjkTpZ7tu9erxHTP6QpGoH7uGhL12hL5RjB2WpiZ+eROOXMMBg4Yp06mJg3XX+SBpTvdqmV7YKgY+92Nb16fi45VuC4xfRild5W979M/HqPPtnAn8FYWzAfbK5DKQtFdZbWvzDivPtGHq5n5tC11kkXi+dRh1Ufpwk8rD1QW/7+Dt61eR/hnH4TFY6QqdnjVGFQvyCCqsmmeH6fEDaG9GiPnD6q+M9PhN4+Q08qVPyeDGVgvb8B9ip+T3qnEfIAAAAASUVORK5CYII=
 workSheet["!images"] = [{
 name: 'image.png',
 data: datapng,
 opts: {
 base64: true
 },
 type: "png",
 position: {
 type: 'twoCellAnchor',
 attrs: {
 editAs: 'oneCell'
 },
 from: {
 col: 3,
 row: 3
 },
 to: {
 col: 6,
 row: 6
 }
 }
 }];
 return workSheet;
 };
 
export default {
 buildSheetFromMatrix,
 isBoolean,
 isNumber,
 isString,
 isObject,
 isCellDescriptor
 };index.jsimport XLSX from 'xlsx';
 import helpers from './helpers';
 let buildSheetFromMatrix = helpers.buildSheetFromMatrix
 let isString = helpers.isString
 
function parse(mixed, options = {}) {
 
const workSheet = XLSX[isString(mixed) ? 'readFile' : 'read'](mixed, {
 cellDates: true
 });
 return Object.keys(workSheet.Sheets).map((name) => {
 const sheet = workSheet.Sheets[name];
 return {
 name,
 data: XLSX.utils.sheet_to_json(sheet, {
 header: 1,
 raw: true
 }),
 worksheet: workSheet
 };
 });
 }
 
function build(worksheets, options = {}) {
 const defaults = {
 bookType: 'xlsx',
 bookSST: false,
 type: 'binary'
 };
 const workBook = new Workbook();
 worksheets.forEach((worksheet) => {
 const name = worksheet.name || 'Sheet';
 const data = buildSheetFromMatrix(worksheet.data || [], options);
 workBook.SheetNames.push(name);
 workBook.Sheets[name] = data;
 });
 options.Custprops && (workBook.Custprops = options.Custprops);
 options.Props && (workBook.Props = options.Props);
 return XLSX.write(workBook, Object.assign({}, defaults, options));
 }
 
function writeFile(worksheets, filename, options = {}) {
 const defaults = {
 bookType: 'xlsx',
 bookSST: false,
 type: 'binary'
 };
 const workBook = new Workbook();
 worksheets.forEach((worksheet) => {
 const name = worksheet.name || 'Sheet';
 const data = buildSheetFromMatrix(worksheet.data || [], options);
 workBook.SheetNames.push(name);
 workBook.Sheets[name] = data;
 });
 options.Custprops && (workBook.Custprops = options.Custprops);
 options.Props && (workBook.Props = options.Props);
 let excel_data = XLSX.write(workBook, Object.assign({}, defaults, options));
 let buf = new ArrayBuffer(excel_data.length);
 let bufView = new Uint8Array(buf);
 for (var i = 0; i < excel_data.length; ++i) {
 bufView[i] = excel_data.charCodeAt(i) & 255;
 }
 const elink = document.createElement("a"); // 创建a标签
 elink.download = filename;
 elink.style.display = "none";
 const blob = new Blob([buf], {
 type: "application/octet-stream"
 });
 elink.href = URL.createObjectURL(blob);
 document.body.appendChild(elink);
 elink.click(); // 触发点击a标签事件
 document.body.removeChild(elink);
 }
 let Workbook = function () {
 this.SheetNames = [];
 this.Sheets = {};
 }
 export default {
 parse,
 writeFile,
 build
 };这个两个文件，在你项目excel文件夹下新建一下，导出的案例是：import node_xlsx from "./excel/index";
 然后在你具体的按钮事件里面调用即可。我的项目并没有用到图片功能，我在helper里面给你加了图片的，你借鉴一下。
 let ws = {};
 ws["!rows"] = [
 {
 hidden: false
 }
 ];
 ws["!cols"] = [];
 ws.Custprops = {};
 let data = [
 this.format_ins_view_column.map(i => {
 return i.title;
 }),
 ...deepCopy(this.filterdata_distinct)
 .filter(row => {
 if (this.cmdb.ins_view_selectedIds.size == 0) {
 return true;
 }
 return this.cmdb.ins_view_selectedIds.has(row.ins.id);
 })
 .map(row => {
 let temp = [];
 this.format_ins_view_column.map(i => {
 temp.push(get_attr_value(row[i.key]));
 });
 return temp;
 })
 ];
 for (var n = 0; n != data[0].length; ++n) {
 ws["!cols"].push({
 wpx: 150
 });
 }
 ws["!merges"] = "auto";
 let excel_data = node_xlsx.writeFile(
 [
 {
 name: "视图数据",
 data: data
 }
 ],
 "视图数据导出" +
 new Date() +
 ".xlsx",
 ws
 );
 `
 最终效果：

**Comment by myseemylife** [comment]
`buildSheetFromMatrix(data,opts)`按照data = [] 传参 报错了~

**Comment by myseemylife** [comment]
感谢大佬~代码已经调通了~

**Comment by FRZ5201314** [comment]
@yaomingdan 大佬，我导出图片的时候分页只能第一页显示多张图片，后面的sheet都不能正确显示图片是什么问题呢。 解压缩xlsx文件查看图片都有导出来，但是除了第一页能正常显示图片，后面的页都没有显示图片。求大佬帮忙
